name: preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CSV_URL: 'Eksperimen_SML_Haifa-Syabina/personality_dataset.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup python
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Jalankan script preprocessing
      - name: Run preprocessing script
        run: python preprocessing/automate_Haifa-Syabina.py

      # Upload hasil dataset preprocessing
      - name: Upload processed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/data_preprocessing.csv

      # - name: Get latest MLflow run_id
      #   id: get_run_id
      #   run: |
      #     RUN_ID=$(ls -td mlruns/0/*/ | head -1 | xargs basename)
      #     echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # - name: Upload to GitHub Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mlflow-run
      #     path: mlruns/

      # - name: Build Docker Model
      #   run: |
      #     run_id=${{ steps.get_run_id.outputs.run_id }}
      #     mlflow models build-docker -m mlruns/0/$run_id/artifacts/model -n ${{ secrets.DOCKER_USERNAME }}/mlflow-model

      # - name: Log in to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Tag Docker Image
      #   run: |
      #     docker tag ${{ secrets.DOCKER_USERNAME }}/mlflow-model ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
      #     docker tag ${{ secrets.DOCKER_USERNAME }}/mlflow-model ${{ secrets.DOCKER_USERNAME }}/mlflow-model:${{ steps.get_run_id.outputs.run_id }}

      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:${{ steps.get_run_id.outputs.run_id }}
